### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by lucidrains** [lucidrains/autoregressive-diffusion-pytorch#5]
- [ ] try creating a custom small unet instead of using mlp
- [ ] use small linear cross attention to all tokens of the past within the denoising network
- [ ] add ema, also add velocity consistency for flow version
